# Generated by Django 4.1.7 on 2023-03-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ratings", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="rating", options={"ordering": ["-timestamp"]}
        ),
        migrations.RenameField(
            model_name="rating", old_name="timestamps", new_name="timestamp"
        ),
    ]
