# Generated by Django 4.1.7 on 2023-03-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ratings", "0002_alter_rating_options_and_more")]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="active_update_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
