# Generated by Django 4.1.7 on 2023-03-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("movies", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating_avg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
